### ISSUE TITLE
createNew fails with: undefined is not a constructor

### ISSUE THREAD

**Issue by aaweb** [KallynGowdy/nativescript-plugin-firebase#1] opened 2016-03-26 17:05 UTC
Hello there

I'm trying to instantiate like in the sample code:

```
  var Firebase = require("nativescript-plugin-firebase-common").Firebase;

  var firebase = Firebase.createNew({
    url: 'https://resplendent-fire-4211.firebaseio.com'
  });
```

However, it fails with:

```
file:///app/tns_modules/angular2/src/facade/exception_handler.js:79:28: JS ERROR TypeError: undefined is not a constructor (evaluating 'new IosFirebaseClass(arg.url)')
```

I tried with my own firebase URL as well with no success. Am I missing something?

Cheers,
Andy

**Comment by KallynGowdy** [comment] 2016-03-27 21:35
No, you are not missing anything. I'm  pretty sure I know what the problem is (which I will describe below), but I haven't been able to test iOS support because that I do not own any iOS devices myself.

I am quite certain that the issue relates to the implementation not grabbing the `Firebase` global object and storing it as `IosFirebaseClass` properly.

The problem is a naming conflict. Firebase named their core Firebase SDK class `Firebase`, which is also the name of my wrapper. Because NativeScript exports all the iOS classes into the global context, I am unable to name my own variable `Firebase` without hiding the global one. 

As a result, it is difficult to export a variable from the module named `Firebase` while using the globally defined variable named `Firebase`. TypeScript seems to ignore this possibility, and I have not found a way to access iOS APIs via a nativescript-specific namespace such as `nativescript.ios`.

As a result, the only fix that I am aware that might work is to use the `global.Firebase` syntax from NodeJS. I am not sure if NativeScript supports such syntax, but I assume that because it uses NPM modules that it also uses the Node runtime.

So, I will attempt that fix and get it uploaded to NPM. From there, you should be able to download it and test it out. In addition, if you want to attempt your own fix, I would be happy to accept it.

**Comment by KallynGowdy** [comment] 2016-03-27 21:41
@aaweb Version 0.9.8 has just been published with the attempted fix.

If the fix works for you, let me know and I will then close this issue. If it doesn't, your additional support would be appreciated to help me resolve the problem. If you do not respond in a week, I will close this issue. (You will still be able to comment)

**Comment by aaweb** [comment] 2016-03-28 10:48
@KallynGowdy It no longer fails on createNew, however, it does not seem to return any object at all:

Code:

```
let Firebase = require('nativescript-plugin-firebase-common').Firebase;
let firebase = Firebase.createNew({
  url: 'https://myfirebase...'
});

console.log('----------');
console.log('A: ', Firebase);
console.log('B: ', firebase);
console.log('----------');
var child = firebase.child('/some/path');
```

Result:

```
CONSOLE LOG file:///app/frameworks/firebase.framework/index.js:6:12: ----------
CONSOLE LOG file:///app/frameworks/firebase.framework/index.js:7:12: A: function IosFirebase(instance) {

            _super.call(this, instance);

        }
CONSOLE LOG file:///app/frameworks/firebase.framework/index.js:8:12: B:
CONSOLE LOG file:///app/frameworks/firebase.framework/index.js:10:12: ----------
JS ERROR TypeError: firebase.child is not a function. (In 'firebase.child('/some/path')', 'firebase.child' is undefined)
```

Another more general question about the plug-in: Since it is using the actual SDK on each platform, are features like offline support working or are there any specific things to pay attention to? Or what are the differences from this to something like angularfire2?

**Comment by KallynGowdy** [comment] 2016-03-28 22:09
I just found another issue and published the attempted fix as v0.9.9.

If you could let me know if it works, I would be very grateful. It's a pretty ghetto way to test things, but AFAIK, it is the only way for me to get things fixed for iOS support.

**Comment by KallynGowdy** [comment] 2016-03-28 22:16
Also, the main differences between this project and angularfire2 is that the angularfire2 project is targeted specifically towards using the Firebase JavaScript API for Angular 2. This project is aimed at reasonably mimicking the [Firebase JavaScript API](https://www.firebase.com/docs/web/api/) as an abstraction between the Firebase iOS and Android SDKs.

Ideally, this means that you could use angularfire2 with this project so that you utilize the native SDKs on mobile, but the JavaScript version on the web with very few code changes.

**Comment by aaweb** [comment] 2016-03-29 10:56
@KallynGowdy That worked beautifully, thanks a lot!

Yes, I guess if you don't have a Mac, there's no easy way to test it. Happy to help out running certain things through the simulator or my devices.

Are you aware of anyone already using angularfire2 with this and if it works together? Or is that more of a longer term goal?

**Closed as completed** 2016-03-29 10:56 UTC
Labels: bug

**Comment by KallynGowdy** [comment] 2016-03-29 18:29
@aaweb  No, I am not aware if this project works with angularfire2. I do know that the integration between [ng2-firebase](https://github.com/KallynGowdy/ng2-firebase) (My own wrapper around Firebase, it's really more of a rx-firebase project than an angular one though) and the plugin works, but when using the NativeScript Angular 2 renderer with observables, the reliability is very spotty. 

The problems appeared to be related to using push change detection instead of the default angular change detection behavior. This may already be fixed, but I haven't been able to test in about half a month.
